version: "3.7"
services:
  # API server
  pxe_server:
    container_name: pxe-server
    image: pxeboot-ubuntu-20.04:latest
    env_file:
      - ./.env
    ports:
      - 67:67/udp
      - 69:69/udp
      - 53:53
    network_mode: "host"

  http_server:
    container_name: http-server
    image: nginx
    env_file:
      - ./.env
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ${foscal}:/var/www/html/focal-live-server-amd64.iso
    ports:
      - 80:80
  